Sync from teddy at 30.07.2025 -- 13:30

diff --git a/ansible/files/bash/scripts/tx b/ansible/files/bash/scripts/tx
--- a/ansible/files/bash/scripts/tx
+++ b/ansible/files/bash/scripts/tx
@@ -12,26 +12,26 @@
 ## bootstrap
 export BIN=$(readlink -f $0)
 export DIR=$(dirname $BIN)
-export SCRIPTS_DIR="$DIR/tx.d"
+export DDIR="$DIR/tx.d"
 export EDITOR=${EDITOR:-vi}
 [ -x $HOME/bin/nvim ] && EDITOR=$HOME/bin/nvim
 ## bootstrap
 
 case "$1" in
-  "ls")
-    cd $SCRIPTS_DIR && ls -1 && cd - >/dev/null 2>&1
-    ;;
-  "rm")
-    rm -f $SCRIPTS_DIR/$2
-    ;;
-  ""|"h"|"help")
-    cat $SCRIPTS_DIR/help.md
-    ;;
-  "e"|"edit")
-    [[ "$2" != "" ]] && $EDITOR $SCRIPTS_DIR/$2 || echo " [ERROR] Specify filter name"
-    ;;
-  *)
-    NAME=$1
-    shift && source $SCRIPTS_DIR/$NAME $@
-    ;;
+"ls")
+  cd $DDIR && ls -1 && cd - >/dev/null 2>&1
+  ;;
+"rm")
+  rm -f $DDIR/$2
+  ;;
+"" | "h" | "help")
+  cat $DDIR/help.md
+  ;;
+"e" | "edit")
+  [[ "$2" != "" ]] && $EDITOR $DDIR/$2 || echo " [ERROR] Specify filter name"
+  ;;
+*)
+  NAME=$1
+  shift && source $DDIR/$NAME $@
+  ;;
 esac
