Sync from teddy at 26.09.2025 -- 15:56

diff --git a/ansible/files/bash/scripts/ax.d/dconf b/ansible/files/bash/scripts/ax.d/dconf
--- a/ansible/files/bash/scripts/ax.d/dconf
+++ b/ansible/files/bash/scripts/ax.d/dconf
@@ -3,21 +3,25 @@
 SHORTCUTS_FILE="$DF_DIR/dconf/keyboard-shortcuts.dconf"
 SHORTCUTS_PATH="/org/cinnamon/desktop/keybindings/"
 
-if [[ "$(which dconf)" == "" ]]; then
-  echo "dconf not found"
-fi
+check_for_dconf() {
+  [[ "$(which dconf)" == "" ]] && (echo "dconf not found"; exit 1)
+}
+
+run_export() {
+  mkdir -p "$DF_DIR/dconf"
+  dconf dump "$SHORTCUTS_PATH" >$SHORTCUTS_FILE
+}
+
+run_import() {
+  if [ -f $SHORTCUTS_FILE ]; then
+    cat $SHORTCUTS_FILE | dconf load "$SHORTCUTS_PATH"
+  fi
+}
+
+check_for_dconf
 
 case "$1" in
-  "export")
-    mkdir -p "$DF_DIR/dconf"
-    dconf dump "$SHORTCUTS_PATH" >$SHORTCUTS_FILE
-    ;;
-  "import")
-    if [ -f $SHORTCUTS_FILE ]; then
-      cat $SHORTCUTS_FILE | dconf load "$SHORTCUTS_PATH"
-    fi
-    ;;
-  "debug")
-    cat $SHORTCUTS_FILE
-    ;;
+  "export") run_export ;;
+  "import") run_import ;;
+  "debug") cat $SHORTCUTS_FILE ;;
 esac
