Sync from teddy at 03.03.2026 -- 11:06

diff --git a/ansible/files/bash/scripts/ax.d/sync b/ansible/files/bash/scripts/ax.d/sync
--- a/ansible/files/bash/scripts/ax.d/sync
+++ b/ansible/files/bash/scripts/ax.d/sync
@@ -11,8 +11,10 @@ __try_to() {
   if [[ "$?" == "0" ]]; then
     echo -e "${bold_green}done${reset}"
   else
+    echo "${bold_red}failure${reset}"
     echo " > GOT ERRORS"
     echo -e "${bold_red}$OUTPUT${reset}"
+    exit 1
   fi
 }
 
